In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import SequentialFeatureSelector

from imblearn.pipeline import Pipeline
from sklearn.model_selection import RepeatedStratifiedKFold, cross_val_score

In [2]:
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_row", 160)
pd.set_option('max_colwidth', 200)

In [3]:
data = pd.read_csv('../../Data/20x44_D.csv')

In [4]:
data.head(5)

loan_amnt  annual_inc       dti  fico_range_low  fico_range_high  int_rate  \
0   1.511139   -0.223515  0.946930       -0.175524        -0.175524  1.241699   
1   0.564527    0.110293 -0.431794       -0.847996        -0.847996 -0.799780   
2  -0.129656   -0.159138  1.715609        0.945262         0.945262 -0.799780   
3  -0.066548    0.044724 -0.397967       -0.175524        -0.175524 -0.799780   
4   1.511139   -0.151985  0.534013        0.496947         0.496947  1.241699   

   installment  open_acc  total_acc  revol_bal  inq_last_6mths  delinq_2yrs  \
0     2.175892 -0.088824   0.195374   0.650273        0.162822    -0.392640   
1     0.213470  0.612170   0.277261  -0.042050       -0.815670     0.687894   
2     0.136280 -0.439322  -0.623493   0.354388       -0.815670    -0.392640   
3    -0.326487  0.436922   1.096127  -0.415254       -0.815670     1.768427   
4     2.175892  0.787419   1.423674   1.199929        2.119807     0.687894   

   acc_now_delinq  collections_12_mths_ex_med  tot_coll_amt  tot_cur_bal  \
0       -0.060009                   -0.142227     -0.013729     0.182902   
1       -0.060009                   -0.142227     -0.013729    -0.011647   
2       -0.060009                   -0.142227     -0.013729    -0.534775   
3       -0.060009                   -0.142227     -0.013729     1.500886   
4       -0.060009                   -0.142227     -0.013729    -0.541927   

    pub_rec  months_cr_line      term  initial_list_status  grade  sub_grade  \
0 -0.405876        0.390609 -0.848851             0.698931    0.0   0.655895   
1 -0.405876       -0.805105  1.178063             0.698931    0.0  -1.524634   
2 -0.405876       -0.549710 -0.848851             0.698931    0.0  -1.524634   
3 -0.405876        0.297738  1.178063             0.698931    0.0  -1.524634   
4 -0.405876        0.100387 -0.848851             0.698931    0.0   0.655895   

   emp_length       ANY  MORTGAGE       OWN      RENT       car  credit_card  \
0    1.151668 -0.019956 -0.873672  2.604210 -0.883202 -0.104626    -0.392277   
1    1.151668 -0.019956 -0.873672  2.604210 -0.883202 -0.104626    -0.392277   
2   -0.361745 -0.019956 -0.873672 -0.383994  1.132244  9.557873    -0.392277   
3    1.151668 -0.019956  1.144595 -0.383994 -0.883202 -0.104626    -0.392277   
4    1.151668 -0.019956  1.144595 -0.383994 -0.883202 -0.104626    -0.392277   

   debt_consolidation  home_improvement     house  major_purchase   medical  \
0            0.812980         -0.245324 -0.105786       -0.161171 -0.131657   
1           -1.230043         -0.245324  9.453027       -0.161171 -0.131657   
2           -1.230043         -0.245324 -0.105786       -0.161171 -0.131657   
3            0.812980         -0.245324 -0.105786       -0.161171 -0.131657   
4           -1.230043         -0.245324 -0.105786       -0.161171 -0.131657   

     moving     other  renewable_energy  small_business  vacation   wedding  \
0 -0.115377 -0.338908         -0.033405       -0.126882 -0.093131 -0.042832   
1 -0.115377 -0.338908         -0.033405       -0.126882 -0.093131 -0.042832   
2 -0.115377 -0.338908         -0.033405       -0.126882 -0.093131 -0.042832   
3 -0.115377 -0.338908         -0.033405       -0.126882 -0.093131 -0.042832   
4 -0.115377  2.950650         -0.033405       -0.126882 -0.093131 -0.042832   

   Not Verified  Source Verified  Verified  loan_status_bin  
0     -0.520822        -0.774070  1.194790              1.0  
1     -0.520822         1.291872 -0.836967              1.0  
2     -0.520822        -0.774070  1.194790              0.0  
3     -0.520822         1.291872 -0.836967              0.0  
4     -0.520822         1.291872 -0.836967              0.0

In [5]:
data.shape

(12560, 44)

In [6]:
data.loan_status_bin.value_counts()

1.0    8447
0.0    4113
Name: loan_status_bin, dtype: int64

In [7]:
#Null Model (or random investment) will yield, 59.3% of picking a good loan: 
data.loan_status_bin.value_counts()[1] / len(data)

0.6725318471337579

In [8]:
X = data.drop('loan_status_bin', axis=1)
X.shape

(12560, 43)

In [9]:
y = data['loan_status_bin']

In [10]:
n_features = 1
lr = LogisticRegression()
sfs = SequentialFeatureSelector(lr, n_features_to_select=n_features)

In [11]:
sfs.fit(X,y)

SequentialFeatureSelector(estimator=LogisticRegression(),
                          n_features_to_select=1)

In [12]:
#sfs.get_support()

In [13]:
print("Top {} features selected by forward sequential selection:{}"\
      .format(n_features, list(X.columns[sfs.get_support()])))


Top 1 features selected by forward sequential selection:['loan_amnt']


In [14]:
feat = list(X.columns[sfs.get_support()])
feat

['loan_amnt']

In [15]:
X_feat = data[feat]

In [16]:
y = data['loan_status_bin']
y

0        1.0
1        1.0
2        0.0
3        0.0
4        0.0
        ... 
12555    1.0
12556    0.0
12557    1.0
12558    1.0
12559    1.0
Name: loan_status_bin, Length: 12560, dtype: float64

In [17]:
lr_check = LogisticRegression()
steps = [('model', lr_check)]
pipeline = Pipeline(steps=steps)

In [18]:
#Accuracy:

cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=1, random_state=1)
scores = cross_val_score(pipeline, X_feat, y, scoring='accuracy', cv=cv, n_jobs=-1) 
print(scores)

score = np.mean(scores)
print(score)

[0.6727707  0.6727707  0.67237261 0.67237261 0.67237261]
0.672531847133758


In [19]:
from sklearn.ensemble import AdaBoostClassifier
ada = AdaBoostClassifier()
steps2 = [('model', ada)]
pipeline2 = Pipeline(steps=steps2)

In [20]:
#Accuracy:

cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=1, random_state=1)
scores = cross_val_score(pipeline2, X_feat, y, scoring='accuracy', cv=cv, n_jobs=-1) 
print(scores)

score = np.mean(scores)
print(score)

[0.6727707  0.6727707  0.67237261 0.67237261 0.67237261]
0.672531847133758


In [21]:
from sklearn.neural_network import MLPClassifier
nn = MLPClassifier(alpha=1, max_iter=1000)
steps3 = [('model', nn)]
pipeline3 = Pipeline(steps=steps3)

In [22]:
#Accuracy:

cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=1, random_state=1)
scores = cross_val_score(pipeline3, X_feat, y, scoring='accuracy', cv=cv, n_jobs=-1) 
print(scores)

score = np.mean(scores)
print(score)

[0.6727707  0.6727707  0.67237261 0.67237261 0.67237261]
0.672531847133758


In [23]:
from sklearn.ensemble import GradientBoostingClassifier
gb = GradientBoostingClassifier()
steps4 = [('model', gb)]
pipeline4 = Pipeline(steps=steps4)

In [24]:
#Accuracy:

cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=1, random_state=1)
scores = cross_val_score(pipeline4, X_feat, y, scoring='accuracy', cv=cv, n_jobs=-1) 
print(scores)

score = np.mean(scores)
print(score)

[0.67117834 0.66759554 0.6727707  0.67157643 0.67038217]
0.6707006369426751
