In [15]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import SequentialFeatureSelector

from imblearn.pipeline import Pipeline
from sklearn.model_selection import RepeatedStratifiedKFold, cross_val_score

In [16]:
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_row", 160)
pd.set_option('max_colwidth', 200)

In [17]:
data = pd.read_csv('../../Data/20x44_DE.csv')

In [18]:
data.head(5)

loan_amnt  annual_inc       dti  fico_range_low  fico_range_high  int_rate  \
0   0.606309    0.606130  0.035808       -1.068212        -1.068212 -0.986813   
1   1.847046    0.774764  1.783361        0.837623         0.837623 -0.986813   
2   0.163188   -0.321359 -0.521897        0.837623         0.837623 -0.433996   
3  -0.037519   -0.456266  0.225909       -0.115295        -0.115295 -0.433996   
4   1.117201    0.167680  1.963155        0.837623         0.837623 -0.986813   

   installment  open_acc  total_acc  revol_bal  inq_last_6mths  delinq_2yrs  \
0     0.287230 -0.133221  -0.047127   0.205624       -0.867990    -0.383964   
1     1.380044  2.362517   2.382457  -0.101756       -0.867990     0.696178   
2     0.617784 -0.133221   0.114845  -0.470743        0.922834    -0.383964   
3    -0.247858 -0.311488   0.195831  -0.472931        0.027422    -0.383964   
4     0.737218  1.827716   2.220485   2.561753        0.027422    -0.383964   

   acc_now_delinq  collections_12_mths_ex_med  pub_rec  months_cr_line  \
0       -0.069702                   -0.125211 -0.37762        2.003373   
1       -0.069702                   -0.125211 -0.37762        0.842595   
2       -0.069702                   -0.125211 -0.37762        0.463565   
3       -0.069702                   -0.125211  1.23937        0.368808   
4       -0.069702                   -0.125211 -0.37762        0.131914   

       term  initial_list_status     grade  sub_grade  emp_length       ANY  \
0  0.863576             0.978751  0.482775   0.755624   -0.927085 -0.019008   
1  0.863576             0.978751  0.482775   0.755624    0.605102 -0.019008   
2 -1.157976            -1.021711  0.482775   1.287329   -1.437814 -0.019008   
3  0.863576             0.978751  0.482775   1.287329    1.115831 -0.019008   
4  0.863576             0.978751  0.482775   0.755624    1.115831 -0.019008   

   MORTGAGE      NONE     OTHER       OWN      RENT        car  credit_card  \
0 -0.911567 -0.003879 -0.006719  2.781231 -0.870794  11.590255     -0.36524   
1  1.097012 -0.003879 -0.006719 -0.359553 -0.870794  -0.086279     -0.36524   
2  1.097012 -0.003879 -0.006719 -0.359553 -0.870794  -0.086279     -0.36524   
3 -0.911567 -0.003879 -0.006719 -0.359553  1.148377  -0.086279     -0.36524   
4 -0.911567 -0.003879 -0.006719 -0.359553  1.148377  -0.086279     -0.36524   

   debt_consolidation  home_improvement     house  major_purchase   medical  \
0           -1.302022         -0.251026 -0.105686       -0.144603 -0.125725   
1            0.768036         -0.251026 -0.105686       -0.144603 -0.125725   
2            0.768036         -0.251026 -0.105686       -0.144603 -0.125725   
3           -1.302022         -0.251026 -0.105686        6.915465 -0.125725   
4            0.768036         -0.251026 -0.105686       -0.144603 -0.125725   

     moving     other  renewable_energy  small_business  vacation   wedding  \
0 -0.113695 -0.319218         -0.034935       -0.152178 -0.088896 -0.051386   
1 -0.113695 -0.319218         -0.034935       -0.152178 -0.088896 -0.051386   
2 -0.113695 -0.319218         -0.034935       -0.152178 -0.088896 -0.051386   
3 -0.113695 -0.319218         -0.034935       -0.152178 -0.088896 -0.051386   
4 -0.113695 -0.319218         -0.034935       -0.152178 -0.088896 -0.051386   

   Not Verified  Source Verified  Verified  loan_status_bin  
0      2.401683        -0.786521 -0.941810              0.0  
1     -0.416375         1.271422 -0.941810              1.0  
2      2.401683        -0.786521 -0.941810              0.0  
3     -0.416375        -0.786521  1.061786              0.0  
4     -0.416375         1.271422 -0.941810              0.0

In [19]:
data.shape

(66449, 44)

In [20]:
data.loan_status_bin.value_counts()

1.0    41777
0.0    24672
Name: loan_status_bin, dtype: int64

In [21]:
#Null Model (or random investment) will yield, 59.3% of picking a good loan: 
data.loan_status_bin.value_counts()[1] / len(data)

0.6287077307408689

In [22]:
X = data.drop('loan_status_bin', axis=1)
X.shape

(66449, 43)

In [23]:
y = data['loan_status_bin']

In [24]:
n_features = 1
lr = LogisticRegression()
sfs = SequentialFeatureSelector(lr, n_features_to_select=n_features)

In [25]:
sfs.fit(X,y)

SequentialFeatureSelector(estimator=LogisticRegression(),
                          n_features_to_select=1)

In [26]:
#sfs.get_support()

In [27]:
print("Top {} features selected by forward sequential selection:{}"\
      .format(n_features, list(X.columns[sfs.get_support()])))


Top 1 features selected by forward sequential selection:['open_acc']


In [28]:
feat = list(X.columns[sfs.get_support()])
feat

['open_acc']

In [29]:
X_feat = data[feat]

In [30]:
y = data['loan_status_bin']
y

0        0.0
1        1.0
2        0.0
3        0.0
4        0.0
        ... 
66444    1.0
66445    0.0
66446    1.0
66447    1.0
66448    1.0
Name: loan_status_bin, Length: 66449, dtype: float64

In [31]:
lr_check = LogisticRegression()
steps = [('model', lr_check)]
pipeline = Pipeline(steps=steps)

In [32]:
#Accuracy:

cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=1, random_state=1)
scores = cross_val_score(pipeline, X_feat, y, scoring='accuracy', cv=cv, n_jobs=-1) 
print(scores)

score = np.mean(scores)
print(score)

[0.62866817 0.62866817 0.62881866 0.62874342 0.62871548]
0.6287227797664253


In [33]:
from sklearn.ensemble import AdaBoostClassifier
ada = AdaBoostClassifier()
steps2 = [('model', ada)]
pipeline2 = Pipeline(steps=steps2)

In [34]:
#Accuracy:

cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=1, random_state=1)
scores = cross_val_score(pipeline2, X_feat, y, scoring='accuracy', cv=cv, n_jobs=-1) 
print(scores)

score = np.mean(scores)
print(score)

[0.62866817 0.62859293 0.62874342 0.62874342 0.62886598]
0.6287227820312924


In [35]:
from sklearn.neural_network import MLPClassifier
nn = MLPClassifier(alpha=1, max_iter=1000)
steps3 = [('model', nn)]
pipeline3 = Pipeline(steps=steps3)

In [36]:
#Accuracy:

cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=1, random_state=1)
scores = cross_val_score(pipeline3, X_feat, y, scoring='accuracy', cv=cv, n_jobs=-1) 
print(scores)

score = np.mean(scores)
print(score)

[0.62866817 0.62866817 0.62874342 0.62874342 0.62871548]
0.6287077308574712


In [37]:
from sklearn.ensemble import GradientBoostingClassifier
gb = GradientBoostingClassifier()
steps4 = [('model', gb)]
pipeline4 = Pipeline(steps=steps4)

In [38]:
#Accuracy:

cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=1, random_state=1)
scores = cross_val_score(pipeline4, X_feat, y, scoring='accuracy', cv=cv, n_jobs=-1) 
print(scores)

score = np.mean(scores)
print(score)

[0.62851768 0.62859293 0.62829195 0.62866817 0.62886598]
0.6285873418507055
