In [61]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import SequentialFeatureSelector

from imblearn.pipeline import Pipeline
from sklearn.model_selection import RepeatedStratifiedKFold, cross_val_score

In [25]:
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_row", 160)
pd.set_option('max_colwidth', 200)

In [26]:
data = pd.read_csv('../../Data/20x41.csv')

In [27]:
data.head(5)

loan_amnt  annual_inc       dti  fico_range_low  fico_range_high  int_rate  \
0  -0.872628    0.503581  0.572069        0.682326         0.682323 -0.405165   
1   1.718531    0.772725  1.749064        0.928630         0.928625 -1.135245   
2   0.752113   -0.126322  1.291724       -0.302888        -0.302887  0.946418   
3   0.620448    0.288623  0.434069        2.160147         2.160138 -0.405165   
4  -0.185339   -0.489399  0.197985       -0.056584        -0.056584 -0.768333   

   installment  open_acc  total_acc  revol_bal  inq_last_6mths  delinq_2yrs  \
0    -0.986330  0.012921   0.800766   0.257759        1.655427     0.676995   
1     1.241494  2.298594   2.322233  -0.117413       -0.904407     0.676995   
2     0.680639  1.067847   0.640612   0.202920       -0.051129    -0.380734   
3     0.373911 -0.690363   0.160148   0.413576       -0.904407    -0.380734   
4    -0.392324 -0.338721   0.160148  -0.494239       -0.051129    -0.380734   

   acc_now_delinq  collections_12_mths_ex_med   pub_rec  \
0       -0.076039                   -0.125241 -0.375888   
1       -0.076039                   -0.125241 -0.375888   
2       -0.076039                   -0.125241 -0.375888   
3       -0.076039                   -0.125241 -0.375888   
4       -0.076039                   -0.125241  1.170753   

   earliest_cr_line_month  earliest_cr_line_year      term  \
0               -0.217886              -0.270704  0.690939   
1                0.957605              -0.830117  0.690939   
2               -1.687248               0.288709  0.690939   
3                1.251477              -0.550411  0.690939   
4               -1.393376              -0.270704  0.690939   

   initial_list_status     grade  sub_grade       ANY  MORTGAGE      NONE  \
0              1.03777  0.791627   0.270731 -0.016391  1.090377 -0.008029   
1              1.03777 -0.473750  -0.279696 -0.016391  1.090377 -0.008029   
2              1.03777  0.791627   1.371584 -0.016391 -0.917114 -0.008029   
3              1.03777  0.791627   0.270731 -0.016391  1.090377 -0.008029   
4              1.03777 -0.473750  -0.004483 -0.016391 -0.917114 -0.008029   

      OTHER       OWN      RENT       car  credit_card  debt_consolidation  \
0 -0.008029 -0.356997 -0.868052 -0.079872    -0.338635           -1.339332   
1 -0.008029 -0.356997 -0.868052 -0.079872    -0.338635            0.746641   
2 -0.008029 -0.356997  1.152005 -0.079872    -0.338635            0.746641   
3 -0.008029 -0.356997 -0.868052 -0.079872    -0.338635            0.746641   
4 -0.008029 -0.356997  1.152005 -0.079872    -0.338635           -1.339332   

   home_improvement     house  major_purchase   medical   moving     other  \
0         -0.250197 -0.117242        7.035681 -0.118367 -0.10911 -0.314762   
1         -0.250197 -0.117242       -0.142133 -0.118367 -0.10911 -0.314762   
2         -0.250197 -0.117242       -0.142133 -0.118367 -0.10911 -0.314762   
3         -0.250197 -0.117242       -0.142133 -0.118367 -0.10911 -0.314762   
4         -0.250197 -0.117242        7.035681 -0.118367 -0.10911 -0.314762   

   renewable_energy  small_business  vacation   wedding  loan_status_bin  
0         -0.036377       -0.179301   -0.0771 -0.048454              1.0  
1         -0.036377       -0.179301   -0.0771 -0.048454              1.0  
2         -0.036377       -0.179301   -0.0771 -0.048454              0.0  
3         -0.036377       -0.179301   -0.0771 -0.048454              1.0  
4         -0.036377       -0.179301   -0.0771 -0.048454              0.0

In [28]:
data.shape

(93073, 41)

In [29]:
data.loan_status_bin.value_counts()

1.0    54388
0.0    38685
Name: loan_status_bin, dtype: int64

In [30]:
X = data.drop('loan_status_bin', axis=1)
X.shape

(93073, 40)

In [31]:
y = data['loan_status_bin']

In [46]:
n_features = 10
lr = LogisticRegression()
sfs = SequentialFeatureSelector(lr, n_features_to_select=n_features)

In [47]:
sfs.fit(X,y)

SequentialFeatureSelector(estimator=LogisticRegression(),
                          n_features_to_select=10)

In [48]:
#sfs.get_support()

In [49]:
print("Top {} features selected by forward sequential selection:{}"\
      .format(n_features, list(X.columns[sfs.get_support()])))


Top 10 features selected by forward sequential selection:['annual_inc', 'dti', 'fico_range_low', 'installment', 'open_acc', 'revol_bal', 'term', 'grade', 'sub_grade', 'RENT']


In [51]:
feat = list(X.columns[sfs.get_support()])
feat

['annual_inc',
 'dti',
 'fico_range_low',
 'installment',
 'open_acc',
 'revol_bal',
 'term',
 'grade',
 'sub_grade',
 'RENT']

In [67]:
X_feat = data[feat]

In [68]:
y = data['loan_status_bin']
y

0        1.0
1        1.0
2        0.0
3        1.0
4        0.0
        ... 
93068    0.0
93069    1.0
93070    1.0
93071    1.0
93072    1.0
Name: loan_status_bin, Length: 93073, dtype: float64

In [69]:
lr_check = LogisticRegression()
steps = [('model', lr_check)]
pipeline = Pipeline(steps=steps)

In [70]:
#Accuracy:

cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=1, random_state=1)
scores = cross_val_score(pipeline, X_feat, y, scoring='accuracy', cv=cv, n_jobs=-1) 
print(scores)

score = np.mean(scores)
print(score)

[0.60714478 0.61063658 0.61009938 0.60852047 0.60653272]
0.6085867854223559


In [71]:
from sklearn.ensemble import AdaBoostClassifier
ada = AdaBoostClassifier()
steps2 = [('model', ada)]
pipeline2 = Pipeline(steps=steps2)

In [72]:
#Accuracy:

cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=1, random_state=1)
scores = cross_val_score(pipeline2, X_feat, y, scoring='accuracy', cv=cv, n_jobs=-1) 
print(scores)

score = np.mean(scores)
print(score)

[0.60521085 0.61208703 0.60650013 0.60631783 0.60524337]
0.60707184057148


In [73]:
from sklearn.neural_network import MLPClassifier
nn = MLPClassifier(alpha=1, max_iter=1000)
steps3 = [('model', nn)]
pipeline3 = Pipeline(steps=steps3)

In [74]:
#Accuracy:

cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=1, random_state=1)
scores = cross_val_score(pipeline3, X_feat, y, scoring='accuracy', cv=cv, n_jobs=-1) 
print(scores)

score = np.mean(scores)
print(score)

[0.60644641 0.61197959 0.60864894 0.60782207 0.60545826]
0.6080710532401465


In [76]:
from sklearn.ensemble import GradientBoostingClassifier
gb = GradientBoostingClassifier()
steps4 = [('model', gb)]
pipeline4 = Pipeline(steps=steps4)

In [77]:
#Accuracy:

cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=1, random_state=1)
scores = cross_val_score(pipeline4, X_feat, y, scoring='accuracy', cv=cv, n_jobs=-1) 
print(scores)

score = np.mean(scores)
print(score)

[0.60805802 0.61375235 0.61160355 0.60970237 0.60733856]
0.6100909700879606
